### ISSUE TITLE
resizing card images throws exception

### ISSUE THREAD

**Issue by KadenLNelson** [UndeadxPanda/lor.gg#1]
I'm running into an exception when the card is being drawn to the panel;

```
Exception thrown: 'System.ArgumentException' in System.Drawing.Common.dll: 'Parameter is not valid.'
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   at System.Drawing.Bitmap..ctor(Image original, Int32 width, Int32 height)
   at System.Drawing.Bitmap..ctor(Image original, Size newSize)
   at LOR.Form1.<button1_Click>d__6.MoveNext() in C:\Users\Kaden\git\lor.gg2\Form1.cs:line 97
```

The `new Size(...)` function here is expecting values greater than 0, but when the calculation of the resized width and height is taking place, the height is being returned as 0 because the height that is calculated is floating point value ~0.90 which is returned as 0 when it is casted back to integer value.

**Comment by KadenLNelson** [comment]
https://github.com/UndeadxPanda/lor.gg/blob/master/LOR/LOR/Form1.cs#L97
